# Generated by Django 6.0.5 on 2026-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
